### ISSUE TITLE
"geoip" based blocking rule is erroneously set to :cn instead of :ir in the configs

### ISSUE THREAD

**Issue by OnceUponATimeInAmerica** [meower1/v2meow#3]
The server-side Iran IP blocking (routing) rule has been erroneously set to `geoip:cn` instead of `geoip:ir` in the configs!

**Comment by meower1** [comment]
i really wanna use the  "its not a bug, its a feature" phrase rn but i actually forgot about that 😅 tho i was planning on implanting a script which uses iptables to block iran's ips server side so that it would decrease the server load (since doing it from the v2ray config has some impact as ive heard) so yeah ill block them from the config side until i can implement the script. thanks for the suggestion 🙂

**Comment by meower1** [comment]
fixed <3
